# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mws < Formula
  desc "Manage meta workspaces around independent native git repos"
  homepage "https://github.com/sustinbebustin/mws"
  version "0.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.0/mws_0.1.0_darwin_amd64.tar.gz"
      sha256 "48a0edefcda2344eb46ecd5ed95f6b09daf0e717456dc8acb643fc312045880e"

      define_method(:install) do
        bin.install "mws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.0/mws_0.1.0_darwin_arm64.tar.gz"
      sha256 "ea33b6afc9140d933630539286e833e275a0e964be4cc9f1138fb9e26ac7bcc4"

      define_method(:install) do
        bin.install "mws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.0/mws_0.1.0_linux_amd64.tar.gz"
      sha256 "725bf58d170015be7c27e4c4675c68a690a7625e37e9a13a6500e48d64a95a22"
      define_method(:install) do
        bin.install "mws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.0/mws_0.1.0_linux_arm64.tar.gz"
      sha256 "f97d8777668c60ec0db321a4d31be05ff2f6913bb47a94856b61ab244e0cd2af"
      define_method(:install) do
        bin.install "mws"
      end
    end
  end

  test do
    system "#{bin}/mws", "version"
  end
end
