# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mws < Formula
  desc "Manage meta workspaces around independent native git repos"
  homepage "https://github.com/sustinbebustin/mws"
  version "0.3.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.3.0/mws_0.3.0_darwin_amd64.tar.gz"
      sha256 "b0c7fe934e4214b8240759ffbc398a2b9b5f56113c22c36d2e73af3620a1dc70"

      define_method(:install) do
        bin.install "mws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.3.0/mws_0.3.0_darwin_arm64.tar.gz"
      sha256 "ae18a32ca45f98bb27a8713a8653c158f7d839e3e4d209677746d88b66706493"

      define_method(:install) do
        bin.install "mws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.3.0/mws_0.3.0_linux_amd64.tar.gz"
      sha256 "5083c288508b54459f8a44483e15aeecd12149786ccaddb4486c899e285088c2"
      define_method(:install) do
        bin.install "mws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.3.0/mws_0.3.0_linux_arm64.tar.gz"
      sha256 "6345b9a5df51df1b9e2a0b0ea6749614b37f5fbc388f2a13278a07245e09fd2e"
      define_method(:install) do
        bin.install "mws"
      end
    end
  end

  test do
    system "#{bin}/mws", "version"
  end
end
