# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mws < Formula
  desc "Manage meta workspaces around independent native git repos"
  homepage "https://github.com/sustinbebustin/mws"
  version "0.1.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.1/mws_0.1.1_darwin_amd64.tar.gz"
      sha256 "2f8544386384b36ed499ace4d7f24574135f32520a912e83f5a25845224cfe1b"

      define_method(:install) do
        bin.install "mws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.1/mws_0.1.1_darwin_arm64.tar.gz"
      sha256 "90201b7f7e816bb3afc7bf3912c5f2ec3955e5494bdb9ecbcb3c34bb0c1d6522"

      define_method(:install) do
        bin.install "mws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.1/mws_0.1.1_linux_amd64.tar.gz"
      sha256 "2a9f2072081957a7c6e0829c7fea2fedf315b5a96e1577c3d756025a20e0a961"
      define_method(:install) do
        bin.install "mws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sustinbebustin/mws/releases/download/v0.1.1/mws_0.1.1_linux_arm64.tar.gz"
      sha256 "d0c694244a1445089849308c42701596438f743b7f6b084e19ddb1d9de43ef03"
      define_method(:install) do
        bin.install "mws"
      end
    end
  end

  test do
    system "#{bin}/mws", "version"
  end
end
